//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Division2Sprinter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"This program will keep you always sprinting in Tom Clancy's The Division 2.

Requirements
    Gamepad controller (eg. XBox 360/Elite controller)

Setup
    Change the following settings in the game:
        Settings > Controls > Toggle to Sprint => No
        Settings > Key Mapping > Sprint => LMB (Left Mouse Button)

    (OPTIONAL)
    Moving the thumbstick down while sprinting will cause you to
    do a 180 turn unless you disable the following setting:
        Settings > Controls > 180 Spin Turn => Off

Usage
    Start this program and then start Tom Clancy's The Division 2.
    Whenever your left thumbstick is over 70% in any direction the
    left mouse button will be held down, causing you to sprint.

NOTE
    Start the program with the argument -h for information on how
    to customize controller, mouse button and threshold. Example:
    Division2Sprinter.exe -h")]
        public string Instructions {
            get {
                return ((string)(this["Instructions"]));
            }
            set {
                this["Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ERROR: Controller is not connected.\r\nHint: Do you have an XBox 360/Elite controll" +
            "er attached?\r\nPress any key to quit.")]
        public string ControllerError {
            get {
                return ((string)(this["ControllerError"]));
            }
            set {
                this["ControllerError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Please switch to Tom Clancy\'s The Division 2 and enjoy the game.\r\nReturn to this " +
            "window and press any key to quit.")]
        public string Started {
            get {
                return ((string)(this["Started"]));
            }
            set {
                this["Started"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sprint")]
        public string Sprint {
            get {
                return ((string)(this["Sprint"]));
            }
            set {
                this["Sprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Duration")]
        public string Duration {
            get {
                return ((string)(this["Duration"]));
            }
            set {
                this["Duration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("average duration")]
        public string AverageDuration {
            get {
                return ((string)(this["AverageDuration"]));
            }
            set {
                this["AverageDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ERROR: Threshold percent is not valid.\r\nHint: Threshold percent must be between 2" +
            "5-100.\r\nPress any key to quit.")]
        public string ThresholdError {
            get {
                return ((string)(this["ThresholdError"]));
            }
            set {
                this["ThresholdError"] = value;
            }
        }
    }
}
